spring:
  r2dbc:
    url: ${POSTGRES_URL:r2dbc:postgresql://localhost:5432/mydb}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mydb}